/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Babo
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private Driver d;
    private Connection myCon;
    private static String connectionURL = "jdbc:mysql://localhost:3306/flightmanager?autoReconnect=true&useSSL=false";

    public Frame(Driver d, Connection myCon) {
        this.d = d;
        this.myCon = myCon;
        
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        passLab = new javax.swing.JLabel();
        userLab = new javax.swing.JLabel();
        passText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        logFail = new javax.swing.JLabel();
        addPassengerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        depLab = new javax.swing.JLabel();
        arrLab = new javax.swing.JLabel();
        depBox = new javax.swing.JComboBox();
        arrBox = new javax.swing.JComboBox();
        nextButton = new javax.swing.JButton();
        arrBox2 = new javax.swing.JComboBox();
        arrLab2 = new javax.swing.JLabel();
        depBox2 = new javax.swing.JComboBox();
        depLab2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightplan = new javax.swing.JTable();
        addPassengerPanel2 = new javax.swing.JPanel();
        flightCount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(null);

        loginButton.setBackground(new java.awt.Color(153, 255, 255));
        loginButton.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(410, 170, 120, 50);

        passLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passLab.setText("Password");
        loginPanel.add(passLab);
        passLab.setBounds(380, 90, 82, 17);

        userLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLab.setText("Username");
        loginPanel.add(userLab);
        userLab.setBounds(380, 30, 61, 17);

        passText.setText(" ");
        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });
        loginPanel.add(passText);
        passText.setBounds(380, 120, 170, 20);

        userText.setText(" ");
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });
        loginPanel.add(userText);
        userText.setBounds(380, 60, 170, 20);

        logFail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Babo\\Desktop\\SCHULE\\INSY_4\\Ü1\\loginFailed.jpg")); // NOI18N
        logFail.setText("jLabel3");
        logFail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        logFail.setVisible(false);
        loginPanel.add(logFail);
        logFail.setBounds(360, 230, 210, 50);

        mainPanel.add(loginPanel, "card3");

        addPassengerPanel.setBackground(new java.awt.Color(255, 255, 255));
        addPassengerPanel.setMaximumSize(new java.awt.Dimension(400, 269));
        addPassengerPanel.setMinimumSize(new java.awt.Dimension(400, 269));
        addPassengerPanel.setPreferredSize(new java.awt.Dimension(400, 250));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 24)); // NOI18N
        jLabel2.setText("Add Passenger");

        depLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depLab.setText("Departure Country");

        arrLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arrLab.setText("Arrival Country");

        depBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        depBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        depBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        depBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depBoxActionPerformed(evt);
            }
        });

        arrBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        arrBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        arrBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        arrBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrBoxActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        arrBox2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        arrBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        arrBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        arrBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrBox2ActionPerformed(evt);
            }
        });

        arrLab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arrLab2.setText("Arrival Airport");

        depBox2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        depBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        depBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        depBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depBox2ActionPerformed(evt);
            }
        });

        depLab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depLab2.setText("Departure Airport");

        flightplan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Flightnumber", "Departure Time", "Arrival Time", "Departure Airport", "Arrival Airport", "Planetype"
            }
        ));
        flightplan.setGridColor(new java.awt.Color(0, 0, 0));
        flightplan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(flightplan);

        javax.swing.GroupLayout addPassengerPanelLayout = new javax.swing.GroupLayout(addPassengerPanel);
        addPassengerPanel.setLayout(addPassengerPanelLayout);
        addPassengerPanelLayout.setHorizontalGroup(
            addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPassengerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPassengerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(368, 368, 368)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPassengerPanelLayout.createSequentialGroup()
                        .addGroup(addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPassengerPanelLayout.createSequentialGroup()
                                .addGroup(addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arrLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arrLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depLab)
                                    .addComponent(depBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arrBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arrBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(depBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(addPassengerPanelLayout.createSequentialGroup()
                                .addComponent(depLab2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        addPassengerPanelLayout.setVerticalGroup(
            addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPassengerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPassengerPanelLayout.createSequentialGroup()
                        .addComponent(depLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depLab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(arrLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arrBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arrLab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arrBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(addPassengerPanel, "card2");

        addPassengerPanel2.setBackground(new java.awt.Color(255, 255, 255));

        flightCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flightCount.setText("(Flights found: )");

        javax.swing.GroupLayout addPassengerPanel2Layout = new javax.swing.GroupLayout(addPassengerPanel2);
        addPassengerPanel2.setLayout(addPassengerPanel2Layout);
        addPassengerPanel2Layout.setHorizontalGroup(
            addPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPassengerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightCount, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );
        addPassengerPanel2Layout.setVerticalGroup(
            addPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPassengerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightCount)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        mainPanel.add(addPassengerPanel2, "card4");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), null, new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(141, 141, 141));
        jLabel1.setText("TGM - Flightmanager ©");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu4.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void arrBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrBoxActionPerformed
        try {
            arrBox2.removeAllItems();
            String arrCountry = (String) arrBox.getSelectedItem();
            myCon = DriverManager.getConnection(connectionURL, d.getUser(), d.getPass());
            Statement tempStatement = myCon.createStatement();
            ResultSet temp = tempStatement.executeQuery("SELECT code From countries WHERE name = \"" + arrCountry + "\";");
            temp.next();
            String arrCode = temp.getString("code");
            temp = tempStatement.executeQuery("SELECT name From airports WHERE country = \"" + arrCode + "\" ORDER BY name;");
            while (temp.next()) {
                arrBox2.addItem(temp.getString("name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_arrBoxActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

    }//GEN-LAST:event_nextButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = userText.getText();
        String password = passText.getText();
        if (d.saveData(username.trim(), password.trim())) {
            mainPanel.removeAll();
            mainPanel.add(addPassengerPanel);
            mainPanel.repaint();
            mainPanel.revalidate();

            try {
                myCon = DriverManager.getConnection(connectionURL, d.getUser(), d.getPass());
                Statement tempStatement = myCon.createStatement();
                ResultSet temp = tempStatement.executeQuery("SELECT name FROM countries");
                while (temp.next()) {
                    depBox.addItem(temp.getString("name"));
                }
                temp.beforeFirst();
                while (temp.next()) {
                    arrBox.addItem(temp.getString("name"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            logFail.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void depBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depBoxActionPerformed
        try {
            depBox2.removeAllItems();
            String depCountry = (String) depBox.getSelectedItem();
            myCon = DriverManager.getConnection(connectionURL, d.getUser(), d.getPass());
            Statement tempStatement = myCon.createStatement();
            ResultSet temp = tempStatement.executeQuery("SELECT code From countries WHERE name = \"" + depCountry + "\";");
            temp.next();
            String depCode = temp.getString("code");
            temp = tempStatement.executeQuery("SELECT name From airports WHERE country = \"" + depCode + "\" ORDER BY name;");
            while (temp.next()) {
                depBox2.addItem(temp.getString("name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_depBoxActionPerformed

    private void arrBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrBox2ActionPerformed

    private void depBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depBox2ActionPerformed

    }//GEN-LAST:event_depBox2ActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPassengerPanel;
    private javax.swing.JPanel addPassengerPanel2;
    private javax.swing.JComboBox arrBox;
    private javax.swing.JComboBox arrBox2;
    private javax.swing.JLabel arrLab;
    private javax.swing.JLabel arrLab2;
    private javax.swing.JComboBox depBox;
    private javax.swing.JComboBox depBox2;
    private javax.swing.JLabel depLab;
    private javax.swing.JLabel depLab2;
    private javax.swing.JLabel flightCount;
    private javax.swing.JTable flightplan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logFail;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel passLab;
    private javax.swing.JTextField passText;
    private javax.swing.JLabel userLab;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
